export const ROUTES = {
  home:        '/',
  login:       '/login',
  shop:        (slug: string) => `/shop/${slug}`,
  shopNew:     '/shop/new',
  shopEdit:    (slug: string) => `/shop/${slug}/edit`,
  tag:         (slug: string) => `/tag/${slug}`,
  routes:      '/routes',
  region:      (city: string) => `/region/${city}`,
  profile:     '/profile',
  admin:       '/admin',
  about:       '/about',
  contact:     '/contact',
  terms:       '/terms',
  privacy:     '/privacy',
} as const
