// ===== legacy path import guard (2026-09-18) =====
// 이 스크립트는 event-goods 버킷의 고정 경로에 upsert:true 로 업로드한다.
// 2026-09-18 중복 정리(49세트 / 111멤버 -> 49객체, 58,811,816 B 회수)로 그 경로들이
// 삭제됐다. 그대로 재실행하면 지운 중복이 되살아나거나 기존 객체를 덮어쓴다.
// 업로드를 content-addressed 로 전환하기 전까지 기본 실행을 막는다.
// 스크립트는 기록으로 보존한다. 삭제하지 말 것.
if (process.env.ALLOW_LEGACY_PATH_IMPORT !== 'I-UNDERSTAND-THIS-RECREATES-DUPLICATES') {
  console.error('legacy path import disabled')
  console.error('  script : importGivenEncorePopup.mjs')
  console.error('  reason : event-goods 고정 경로 upsert:true 업로드 - 2026-09-18 dedup 결과를 되돌린다')
  console.error('  unlock : $env:ALLOW_LEGACY_PATH_IMPORT="I-UNDERSTAND-THIS-RECREATES-DUPLICATES"')
  console.error('           해당 PowerShell 세션에서만 유효. setx 로 영구 설정하지 말 것.')
  process.exit(1)
}
// ===== /legacy path import guard =====
import{createClient}from'@supabase/supabase-js';import{config}from'dotenv';import{mkdir,writeFile}from'node:fs/promises';config({path:'../.env.local'});const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY);const title='기븐展 -given exhibition- ENCORE POP UP Shop in Seoul';const old=await db.from('events').select('*').eq('title',title).maybeSingle();if(old.error)throw old.error;await mkdir('scripts/event-backups',{recursive:true});await writeFile(`scripts/event-backups/before-given-encore-${Date.now()}.json`,JSON.stringify(old.data,null,2));const img=await fetch('https://spacegalleria.co.kr/data/file/exhibition/e276abad533f8bdddb6f05478ece91ca_XUGOs1pv_48862a1c8dc6fa635c43dac881ee6791775ff137.jpg');if(!img.ok)throw new Error(`poster ${img.status}`);const p='covers/2026/given-encore-seoul-main-poster.jpg';const up=await db.storage.from('event-goods').upload(p,Buffer.from(await img.arrayBuffer()),{contentType:'image/jpeg',upsert:true});if(up.error)throw up.error;const cover=db.storage.from('event-goods').getPublicUrl(p).data.publicUrl;const hours={mon:{open:'11:00',close:'22:00'},tue:{open:'11:00',close:'22:00'},wed:{open:'11:00',close:'22:00'},thu:{open:'11:00',close:'22:00'},fri:{open:'11:00',close:'22:00'},sat:{open:'10:30',close:'22:00'},sun:{open:'10:30',close:'22:00'}};const event={tag_id:'60acff28-fe8a-4966-898b-c842c35c9353',type:'popup',title,start_date:'2026-08-29',end_date:'2026-09-27',reserve_start:'2026-08-21',reserve_end:null,entry_info:'사전예약 후 입장\n현장 입장 가능',description:'인기 BL 작품 「기븐」의 세계관과 오리지널 굿즈를 만날 수 있는 공식 ENCORE 팝업숍입니다.\n\n사전예약은 지정한 날짜와 시간에만 유효하며 예약 1건당 본인 1명만 입장할 수 있습니다. 현장 입장은 내부 상황과 잔여 인원에 따라 제한될 수 있습니다.',cover_url:cover,place_id:'6c9bad49-7a5b-43d3-b2df-405a2e5df390',place_name:'AK플라자 홍대',place_addr:'서울 마포구 양화로 188',place_lat:37.5578085490102,place_lng:126.926407838298,place_detail:'3층 Space Galleria 서울 홍대',parking:true,parking_note:'주차 가능(유료)\n주중 최초 30분 3,000원, 이후 10분당 1,000원\n주말 최초 30분 5,000원, 이후 30분당 5,000원\n1만원 이상 구매 시 1시간, 3만원 이상 2시간, 5만원 이상 3시간 무료',hours,hours_info:'월~금 11:00~22:00\n주말·공휴일 10:30~22:00\n입장 마감 21:00',source_urls:['https://spacegalleria.co.kr/exhibition/32','https://x.com/SpaceGalleriaKR','https://linktr.ee/SpaceGalleria','https://www.akplaza.com/'],ticket_urls:[{url:'https://booking.naver.com/booking/12/bizes/1704547',label:'팝업 사전예약하기'}],updated_by:'e1ffdf30-345a-42c0-8e85-48eb1f9d915d',updated_at:new Date().toISOString()};const r=old.data?await db.from('events').update(event).eq('id',old.data.id).select('*').single():await db.from('events').insert(event).select('*').single();if(r.error)throw r.error;console.log(JSON.stringify({status:old.data?'UPDATE':'INSERT',id:r.data.id,title:r.data.title,cover_url:r.data.cover_url,ticket_urls:r.data.ticket_urls},null,2))
