import { createClient } from '@supabase/supabase-js'
const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY)
const now=new Date().toISOString()
async function tag(name,slug){let r=await db.from('tags').select('*').eq('slug',slug).maybeSingle();if(r.error)throw r.error;if(!r.data)r=await db.from('tags').select('*').eq('name',name).maybeSingle();if(r.error)throw r.error;if(!r.data)r=await db.from('tags').insert({name,slug}).select('*').single();if(r.error)throw r.error;return r.data}
async function existingPlace(kakao){const r=await db.from('places').select('*').eq('kakao_place_id',kakao).single();if(r.error)throw r.error;return r.data}
async function ensurePlace(row){let r=await db.from('places').select('*').eq('kakao_place_id',row.kakao_place_id).maybeSingle();if(r.error)throw r.error;if(!r.data)r=await db.from('places').insert(row).select('*').single();if(r.error)throw r.error;return r.data}
const [peach,banpresto,ak,ipark]=await Promise.all([tag('PEACH-PIT','peach-pit'),tag('반프레스토','banpresto'),existingPlace('1156421273'),existingPlace('7990380')])
const popcorn=await ensurePlace({slug:'popcon-d-square',name:'팝콘D스퀘어',place_type:'EXHIBITION',addr:'서울 용산구 한강대로23길 55',region:'서울',district:'용산구',lat:37.5288833642705,lng:126.964575728989,kakao_place_id:'1736653963',category_name:'문화,예술 > 미술,공예',parking:ipark.parking,parking_note:ipark.parking_note})
const p=(v,d)=>({place_id:v.id,place_name:v.name,place_addr:v.addr,place_lat:v.lat,place_lng:v.lng,place_detail:d,parking:v.parking,parking_note:v.parking_note})
const events=[
 {tag_id:peach.id,type:'exhibition',title:'PEACH-PIT 25주년 기념 특별전',start_date:'2026-10-24',end_date:'2026-11-29',reserve_start:'2026-08-18',reserve_end:null,entry_info:'예매 후 입장',description:'「캐릭캐릭 체인지!」, 「로젠 메이든」, 「좀비론」, 「디어즈」 등 PEACH-PIT의 25년을 한국 최초 공개 원화와 함께 만나는 특별전입니다.\n\n얼리버드 티켓은 8월 31일까지 판매하며, 입장 마감은 19:00입니다.',cover_url:'https://akcdn-daewonplayd.cafe24img.com/popcondplay/ticket/20260813_peach-pit_early/peach-pit_early_01.jpg',...p(popcorn,'아이파크몰 용산점 6층 대원뮤지엄'),hours:Object.fromEntries(['mon','tue','wed','thu','fri','sat','sun'].map(d=>[d,{open:'10:30',close:'20:00'}])),hours_info:'매일 10:30~20:00\n입장 마감 19:00',source_urls:['https://www.popcondplay.com/ip/news/view/675','https://x.com/haksan_comic'],ticket_urls:[{url:'https://www.popcondplay.com/reserve/view/89',label:'전시 예매하기'}],updated_at:now},
 {tag_id:banpresto.id,type:'popup',title:'반프레스토 × 치비구루미 팝업스토어',start_date:'2026-08-21',end_date:'2026-09-10',reserve_start:null,reserve_end:null,entry_info:'현장 선착순 입장',description:'여러 작품의 치비구루미와 반프레스토 피규어를 만나는 팝업스토어입니다.\n\n치비구루미 2개 이상 구매 특전과 피규어 구매·공식 SNS 팔로우 특전은 준비 수량 소진 시 종료됩니다. 럭키박스는 랜덤 구성으로 구매 후 교환할 수 없습니다.',cover_url:'https://media.orings.co.kr/static/place/2026-08-20/f82800ea-d429-4275-b06c-c17cc91ae304.jpg',...p(ak,'3층'),hours:{mon:{open:'11:00',close:'22:00'},tue:{open:'11:00',close:'22:00'},wed:{open:'11:00',close:'22:00'},thu:{open:'11:00',close:'22:00'},fri:{open:'11:00',close:'22:00'},sat:{open:'10:30',close:'22:00'},sun:{open:'10:30',close:'22:00'}},hours_info:'평일 11:00~22:00\n주말·공휴일 10:30~22:00',source_urls:['https://www.popcondplay.com/ip/news/view/677','https://x.com/ICHIBAN_KUJI_'],ticket_urls:[],updated_at:now},
]
const out=[]
for(const e of events){const old=await db.from('events').select('id').eq('title',e.title).eq('start_date',e.start_date).maybeSingle();if(old.error)throw old.error;const r=old.data?await db.from('events').update(e).eq('id',old.data.id).select('id,title,start_date,end_date,reserve_start,reserve_end,place_name,place_detail,hours_info,entry_info,cover_url,ticket_urls').single():await db.from('events').insert(e).select('id,title,start_date,end_date,reserve_start,reserve_end,place_name,place_detail,hours_info,entry_info,cover_url,ticket_urls').single();if(r.error)throw r.error;out.push({status:old.data?'UPDATE':'INSERT',...r.data})}
console.log(JSON.stringify(out,null,2))
